version: '2'

services:

  node_app:
    container_name: node.dev
    volumes:
     - ./app:/var/www/html/app/
    build:
      #context: ./dockerfiles/
      context: ./
      dockerfile: ./dockerfiles/node.dockerfile.sh

    image: cntmedia/node-google-appscript:1.0.0
    expose:
      - 8080
    ports:
      - 80:8080
